default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  user: postgres
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: escamboapp_development

test:
  <<: *default
  database: escamboapp_test

production:
  <<: *default
  database: escamboapp_production
  username: escamboapp